name: Checks

permissions:
  contents: 'write'

on:
  pull_request:
  workflow_dispatch:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # if you want to cancel runs when a new one is queued, set this to true
  cancel-in-progress: false

defaults:
  run:
    shell: bash

env:
  # Enable debug logging for actions
  ACTIONS_RUNNER_DEBUG: true

jobs:
  checks:
    if: ${{ !contains(github.event.head_commit.message, '[skip-checks]') }}
    runs-on: ['ubuntu-latest']
    steps:
      - name: 🔑 Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 'latest'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: Install Dependencies
        shell: bash
        run: pnpm install --frozen-lockfile

      - name: '🧹 Format & Lint'
        shell: bash
        run: pnpm dlx @biomejs/biome check . --error-on-warnings

      - name: '🧪 Typecheck'
        shell: bash
        run: pnpm typecheck

      - name: '🔧 Build'
        shell: bash
        run: pnpm run build

      - name: '🧪 Test'
        shell: bash
        run: pnpm test
