name: 'Publish to GitHub Pages'

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  pages: write
  contents: read
  id-token: write

concurrency:
  group: 'pages'
  # if you want to cancel runs when a new one is queued, set this to true
  cancel-in-progress: false

defaults:
  run:
    shell: bash

env:
  # Enable debug logging for actions
  ACTIONS_RUNNER_DEBUG: true

jobs:
  deploy:
    environment:
      name: 'github-pages'
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ['ubuntu-latest']
    steps:
      - name: 🔑 Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 'latest'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: 'lts/*'

      - name: Install Dependencies
        shell: bash
        run: pnpm install --frozen-lockfile

      - name: '🔧 Build'
        shell: bash
        run: pnpm run build

      - name: 'Setup Pages'
        uses: actions/configure-pages@v5

      - name: 'Upload Artifact'
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: 'Deploy to GitHub Pages'
        id: deployment
        uses: actions/deploy-pages@v4
